# frozen_string_literal: true

require_relative 'potty/version'
require_relative 'potty/keys'
require_relative 'potty/events'
require_relative 'potty/style'
require_relative 'potty/line_editor'
require_relative 'potty/ansi'
require_relative 'potty/input/decoder'
require_relative 'potty/application'
require_relative 'potty/theme'
require_relative 'potty/layout'
require_relative 'potty/border'
require_relative 'potty/window_manager'
require_relative 'potty/view'
require_relative 'potty/widgets/base'
require_relative 'potty/widgets/container'
require_relative 'potty/widgets/panel'
require_relative 'potty/widgets/list'
require_relative 'potty/widgets/list_item'
require_relative 'potty/widgets/colored_fields_item'
require_relative 'potty/widgets/flash_message'
require_relative 'potty/widgets/status_bar'
require_relative 'potty/widgets/progress_bar'
require_relative 'potty/widgets/label'
require_relative 'potty/widgets/button'
require_relative 'potty/widgets/text_input'
require_relative 'potty/widgets/toggle'
require_relative 'potty/widgets/radio_group'
require_relative 'potty/widgets/checkbox_group'
require_relative 'potty/widgets/countdown'
require_relative 'potty/widgets/spinner'
require_relative 'potty/sprite'
require_relative 'potty/animator'
require_relative 'potty/sprites/sample'
# Mouth's prompt views subclass Potty::View, so load it after the framework.
require_relative 'potty/mouth'

module Potty
end
